apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://portainer.github.io/k8s
    targetRevision: 1.0.63
    chart: portainer
    helm:
      valuesObject:
        service:
          type: ClusterIP
        tls:
          force: false
        ingress:
          enabled: false
  - repoURL: git@github.com:Chelsea486MHz/gitops.git
    targetRevision: main
    path: apps/portainer
    directory:
      include: "ingress.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: portainer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true